version: "3"
services:
  web:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "node  Server/server.js"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
